# Generated by Django 4.2.1 on 2023-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideritem",
            name="link",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
