# Generated by Django 4.2.1 on 2023-06-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_discount_code_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_code',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
