# Generated by Django 4.2.1 on 2023-06-18 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_discount_code_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_code',
            name='for_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
