# Generated by Django 4.2.1 on 2023-06-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_discount_code_for_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount_code',
            name='for_user',
        ),
        migrations.AddField(
            model_name='discount_code',
            name='for_user_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
