# Generated by Django 4.2.1 on 2023-06-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTelegram',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('like_products', models.ManyToManyField(blank=True, related_name='telegram_users_like', to='products.product')),
            ],
            options={
                'verbose_name': 'Telegram profile',
                'verbose_name_plural': 'Telegram profiles',
            },
        ),
    ]
